import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { LEVELS_V1 } from "../src/server/levels/spec";
import { renderLevelSvg } from "./level-renderers";

const root = process.cwd();
const outDir = path.join(root, "public", "levels", "v1");
await mkdir(outDir, { recursive: true });
await mkdir(path.join(root, "src", "levels"), { recursive: true });

for (const level of LEVELS_V1) {
  const svg = renderLevelSvg(level);
  const png = await sharp(Buffer.from(svg), { density: 72 })
    .png({ compressionLevel: 9, adaptiveFiltering: false })
    .toBuffer();
  await writeFile(path.join(root, "public", level.imageUrl), png);
}

const publicLevels = LEVELS_V1.map(({ version, level, gridSize, limitMs, imageUrl, choices }) => ({ version, level, gridSize, limitMs, imageUrl, choices }));
const source = `// Generated by scripts/generate-levels.ts. Do not edit by hand.
// Contains only public level metadata; correct answers live in src/server/levels.
import type { PublicLevel } from "@/game/contracts";

export const PUBLIC_LEVELS_V1: PublicLevel[] = ${JSON.stringify(publicLevels, null, 2)};
`;
await writeFile(path.join(root, "src", "levels", "public-catalog.generated.ts"), source);
console.log(`Generated ${LEVELS_V1.length} level images and the public catalog`);
